ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fee_min INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fee_max INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fee_currency TEXT DEFAULT 'EUR';
